### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by tviel** [federicocasares/cavifree#1]
Hi,

very intersting project. Using it in URP for Unity 6000.4, but get a shader compilation error.

`#include <UnityShaderVariables.cginc>` seems to be missing in the hlsl file to work with the `_ScreenParams `, but even after that, it is complaining, that `SHADERGRAPH_SAMPLE_SCENE_NORMAL(uv)` symbol cannot be resolved. The material renders pink.

Best

**Comment by federicocasares** [comment]
That's really strange. I have just tested it on 6000.5 and it works fine. Can you try one more time?

These are the steps I followed:

1. Create a new URP project using the template.
2. Import the 3 files from the Cavifree URP folder into the project.
3. Fix the broken link in the Custom Function node of the CavityShader shader graph.
4. Create a full screen pass in the Universal Renderer Data asset (inside Assets/Settings).
5. Tweak the settings in the CavityMaterial.

This is the result:

![image](https://github.com/federicocasares/cavifree/assets/3209009/a7e8377c-d266-4895-b95b-c9b3e5cc0ea3)

**Comment by federicocasares** [comment]
@tviel When you have a minute, can you confirm if you have managed to make it work? :)
